# Generated by Django 3.2.13 on 2022-04-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AddField(
            model_name='comments',
            name='level',
            field=models.IntegerField(default=1, verbose_name='уровень вложенности комментария'),
        ),
    ]
