# Generated by Django 4.0.4 on 2022-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_rename_post_comments_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_main',
            field=models.IntegerField(blank=True, null=True, verbose_name='id комментария 3 уровня-родителя'),
        ),
    ]
